server:
  port: ${PORT:${SERVER_PORT:0}}
  servlet:
    context-path: /coe
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_coe
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
